// Users Action Types
export const RECEIVE_USERS_SUCCESS = "RECEIVE_USERS_SUCCESS";
export const RECEIVE_USERS_FAIL = "RECEIVE_USERS_FAIL";
export const RECEIVE_ANSWER_SUCCESS = "RECEIVE_ANSWER_SUCCESS";
export const RECEIVE_ANSWER_FAIL = "RECEIVE_ANSWER_FAIL";
export const USER_ADDED_QUESTION_SUCESS = "USER_ADDED_QUESTION_SUCESS";
export const USER_ADDED_QUESTION_FAIL = "USER_ADDED_QUESTION_FAIL";

// Question Action Types
export const RECEIVE_QUESTIONS_SUCCESS = "RECEIVE_QUESTIONS_SUCCESS";
export const RECEIVE_QUESTIONS_FAIL = "RECEIVE_QUESTIONS_FAIL";
export const CLEAN_QUESTIONS = "CLEAN_QUESTIONS";
export const RECEIVE_VOTE_SUCCESS = "RECEIVE_VOTE_SUCCESS";
export const RECEIVE_VOTE_FAIL = "RECEIVE_VOTE_FAIL";
export const ADD_QUESTION_SUCCESS = "ADD_QUETION_SUCCESS";
export const ADD_QUESTION_FAIL = "ADD_QUESTION_FAIL";

// Auth Action Types
export const SET_AUTHED_USER = "SET_AUTHED_USER";
export const UNAUTH = "UNAUTH";

// Widgets Action Types
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_NOT_LOADING = "SET_IS_NOT_LOADING";
